var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< QString >", "structfmt_1_1formatter_3_01QString_01_4.html", "structfmt_1_1formatter_3_01QString_01_4" ],
      [ "formatter< std::filesystem::path >", "structfmt_1_1formatter_3_01std_1_1filesystem_1_1path_01_4.html", "structfmt_1_1formatter_3_01std_1_1filesystem_1_1path_01_4" ]
    ] ],
    [ "AddGameDialog", "classAddGameDialog.html", "classAddGameDialog" ],
    [ "BatchImportDelegate", "classBatchImportDelegate.html", "classBatchImportDelegate" ],
    [ "BatchImportDialog", "classBatchImportDialog.html", "classBatchImportDialog" ],
    [ "BatchImportModel", "classBatchImportModel.html", "classBatchImportModel" ],
    [ "Database", "classDatabase.html", "classDatabase" ],
    [ "DetailedRecordView", "classDetailedRecordView.html", "classDetailedRecordView" ],
    [ "FileInfo", "structFileInfo.html", "structFileInfo" ],
    [ "FileScanner", "structFileScanner.html", "structFileScanner" ],
    [ "FileScannerGenerator", "structFileScannerGenerator.html", "structFileScannerGenerator" ],
    [ "FlyWeight", "classFlyWeight.html", "classFlyWeight" ],
    [ "GameImportData", "structGameImportData.html", "structGameImportData" ],
    [ "GameMetadata", "structGameMetadata.html", "structGameMetadata" ],
    [ "GroupsOutput", "structGroupsOutput.html", "structGroupsOutput" ],
    [ "ImportPreProcessor", "classImportPreProcessor.html", "classImportPreProcessor" ],
    [ "ImportProcessor", "classImportProcessor.html", "classImportProcessor" ],
    [ "InvalidRecordID", "structInvalidRecordID.html", "structInvalidRecordID" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MetadataAlreadyExists", "structMetadataAlreadyExists.html", "structMetadataAlreadyExists" ],
    [ "MetadataException", "structMetadataException.html", "structMetadataException" ],
    [ "NonTransaction", "structNonTransaction.html", "structNonTransaction" ],
    [ "ProgressBarDialog", "classProgressBarDialog.html", "classProgressBarDialog" ],
    [ "RecordAlreadyExists", "structRecordAlreadyExists.html", "structRecordAlreadyExists" ],
    [ "RecordBannerDelegate", "classRecordBannerDelegate.html", "classRecordBannerDelegate" ],
    [ "RecordData", "structRecordData.html", "structRecordData" ],
    [ "RecordEditor", "classRecordEditor.html", "classRecordEditor" ],
    [ "RecordException", "structRecordException.html", "structRecordException" ],
    [ "RecordListModel", "classRecordListModel.html", "classRecordListModel" ],
    [ "RecordView", "classRecordView.html", "classRecordView" ],
    [ "Search", "classSearch.html", "classSearch" ],
    [ "SettingsDialog", "classSettingsDialog.html", "classSettingsDialog" ],
    [ "Transaction", "structTransaction.html", "structTransaction" ],
    [ "TransactionData", "classTransactionData.html", "classTransactionData" ],
    [ "TransactionInvalid", "structTransactionInvalid.html", "structTransactionInvalid" ]
];