name: "Setup GCC 12.2"
description: "Setup GCC 12.2"

runs:
  using: "composite"
  steps:
    - name: Cache winlib GCC 12.2
      id: cache-gcc
      uses: actions/cache@v3
      with:
        path: '${{github.workspace}}\mingw64'
        key: ${{runner.os}}-mingw64-gcc-12.2.0

    - name: Download winlibs GCC 12.2
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      uses: carlosperate/download-file-action@v2.0.0
      id: download_gcc
      with:
        file-url: https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-15.0.7-10.0.0-ucrt-r4/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r4.zip
        # FUCK    https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.7z
        #                                                                                                              # ITS ALMOST LIKE I HAD THE WRONG VERSION
        file-name: winlibs-gcc.7z
        location: '${{github.workspace}}\mingw64'

    - name: Prepare winlibs GCC 12.2
      shell: powershell
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      run: |
        cd mingw64
        7z x winlibs-gcc.7z
        cd ..

    - name: Add GCC to PATH
      shell: powershell
      run: |
        echo "${{github.workspace}}\mingw64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{github.workspace}}\mingw64\mingw64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

